version: "3"
services:
  client:
    container_name: react_client
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app/
      - /app/node_modules
    depends_on:
      - "server"
  server:
    container_name: flask_server
    image: openmined/opus-server:latest
    build: ./server/
    volumes: ["./server:/server"]
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - "db"
    environment:
      PORT: 5000
      FLASK_CONFIGURATION: development
      FRONTEND_HOST: http://localhost
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:opus_local_5432@db:5432
  db:
    container_name: postgres_db
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: opus_local_5432
    ports:
      - 5432:5432
  ssi:
    container_name: express_ssi
    image: openmined/opus-ssi:latest
    build: ./ssi/
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      PORT: 3002

