"""ssi-tables

Revision ID: a9e4ea515f00
Revises: 8b4e8a2a43bd
Create Date: 2020-04-18 23:11:49.297194

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'a9e4ea515f00'
down_revision = '8b4e8a2a43bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_state',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('invite_url', sa.String(length=2000), nullable=True),
    sa.Column('connection_id', app.database.GUID(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='session_state_user_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_state')
    # ### end Alembic commands ###
